project_id = "qisamkiggoibjkkdtkxq"

[functions.youtube-videos]
verify_jwt = false

[functions.opensea-wallet-nfts]
verify_jwt = false

[functions.printful-products]
verify_jwt = false

[functions.printful-checkout]
verify_jwt = false

[functions.paypal-checkout]
verify_jwt = false

[functions.stream-track]
verify_jwt = false
