/* Generated by lab/music-gen-images.cjs: right-sized WebP copies of the catalog covers.
 * Keys are the cover_art_url values stored in the database; anything not listed here is used as-is. */
export const COVER_MANIFEST: Record<string, { base: string; widths: number[] }> = {
  "/images/art-of-ism-cover.webp": {
    "base": "/images/covers/opt/art-of-ism-cover",
    "widths": [
      480,
      960
    ]
  },
  "/images/big-navi-remix-cover.webp": {
    "base": "/images/covers/opt/big-navi-remix-cover",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/album-cold-ass-pimp.webp": {
    "base": "/images/covers/opt/album-cold-ass-pimp",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/album-grave.webp": {
    "base": "/images/covers/opt/album-grave",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/album-one-on-one.jpg": {
    "base": "/images/covers/opt/album-one-on-one",
    "widths": [
      480
    ]
  },
  "/images/covers/album-ties.webp": {
    "base": "/images/covers/opt/album-ties",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/big-boy-drip.webp": {
    "base": "/images/covers/opt/big-boy-drip",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/bout-to-blow.webp": {
    "base": "/images/covers/opt/bout-to-blow",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/dippin-metaverse.webp": {
    "base": "/images/covers/opt/dippin-metaverse",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/h-town-represent.webp": {
    "base": "/images/covers/opt/h-town-represent",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/limitless.webp": {
    "base": "/images/covers/opt/limitless",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/my-world.webp": {
    "base": "/images/covers/opt/my-world",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/nft-art-of-ism.webp": {
    "base": "/images/covers/opt/nft-art-of-ism",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/panties-on-my-piano.webp": {
    "base": "/images/covers/opt/panties-on-my-piano",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/put-the-dope-down.jpg": {
    "base": "/images/covers/opt/put-the-dope-down",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/social-media-ho-stroll.jpg": {
    "base": "/images/covers/opt/social-media-ho-stroll",
    "widths": [
      480,
      960
    ]
  },
  "/images/covers/southern-sounds.webp": {
    "base": "/images/covers/opt/southern-sounds",
    "widths": [
      480,
      960
    ]
  },
  "/images/today-great-day-cover.png": {
    "base": "/images/covers/opt/today-great-day-cover",
    "widths": [
      480
    ]
  },
  "/images/unsolved-mysteries-cover.jpg": {
    "base": "/images/covers/opt/unsolved-mysteries-cover",
    "widths": [
      480,
      960
    ]
  },
  "https://qisamkiggoibjkkdtkxq.supabase.co/storage/v1/object/public/audio/bet-on-her/Bet%20On%20Her%20(cover%20art).png": {
    "base": "/images/covers/opt/bet-on-her-cover-art",
    "widths": [
      480,
      960
    ]
  }
};
